services:
  psql-finance:
    image: postgres:16-alpine
    env_file: ../.env
    volumes:
      - financedata:/var/lib/postgresql/data
    expose: [ "5432" ]
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  financedata: